services:
  db:
    container_name: pgsql_desafio
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=applicationphp
  php:
    container_name: php_desafio
    build: ./back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./back/src:/var/www/html
      - ./back/logs:/var/log/apache2
    links:
      - db
  pgadmin:
    container_name: pgadmin_desafio
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - ./database/server.json:/pgadmin4/servers.json
    links:
      - db
  node:
    container_name: node_desafio
    build: ./front
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./front:/app
    command: 'npm run dev'

