--Every command here will be executed when the container is created
CREATE TABLE CATEGORIES (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255),
    TAX NUMERIC(10,2),
    ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE PRODUCTS (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255),
    PRICE NUMERIC(10,2),
    CATEGORY_ID INTEGER,
    AMOUNT INTEGER,
    CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID),
    ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE ORDERS (
    ID INTEGER PRIMARY KEY,
    TOTAL NUMERIC(10,2),
    TAX NUMERIC(10,2),
    ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE ORDER_ITEM(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255),
    ORDER_ID INTEGER,
    PRODUCT_ID INTEGER,
    AMOUNT INTEGER,
    PRICE NUMERIC(10,2),
    TAX NUMERIC(10,2),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    ACTIVE INTEGER DEFAULT 1
)